-- ────────────────────────────────────────────────────────────
-- Omarchy Custom Theme for Neovim
-- Generated by Omarchist
-- ────────────────────────────────────────────────────────────

return {
	{ "ficcdaf/ashen.nvim" },
	{
		"LazyVim/LazyVim",
		opts = { colorscheme = "ashen" },
	},
}