#:schema https://yazi-rs.github.io/schemas/theme.json

[mgr]
# tmTheme files can be found here: https://github.com/folke/tokyonight.nvim
syntect_theme = "../bat/themes/tokyonight_night.tmTheme"

border_style = { fg = "#29a4bd" }
cwd = { fg = "#7dcfff" }
find_keyword = { bold = true, fg = "#9ece6a" }
find_position = { fg = "#c0caf5" }
marker_copied = { bg = "#e0af68", fg = "#e0af68" }
marker_cut = { bg = "#f7768e", fg = "#f7768e" }
marker_selected = { fg = "#9ece6a" }
count_selected = { bg = "#9ece6a", fg = "#1a1b26" }
count_copied = { bg = "#e0af68", fg = "#1a1b26" }
count_cut = { bg = "#f7768e", fg = "#1a1b26" }

[cmp]
active = { bg = "#3b4261", fg = "#bb9af7" }
border = { fg = "#7aa2f7" }
inactive = { fg = "#a9b1d6" }

[tabs]
active = { bg = "#7aa2f7", fg = "#1a1b26" }
inactive = { bg = "#292e42", fg = "#a9b1d6" }

[filetype]
rules = [
    { fg = "#7dcfff", mime = "image/*" },
    { fg = "#e0af68", mime = "video/*" },
    { fg = "#e0af68", mime = "audio/*" },
    { fg = "#bb9af7", mime = "application/zip" },
    { fg = "#bb9af7", mime = "application/gzip" },
    { fg = "#bb9af7", mime = "application/x-tar" },
    { fg = "#bb9af7", mime = "application/x-bzip" },
    { fg = "#bb9af7", mime = "application/x-bzip2" },
    { fg = "#bb9af7", mime = "application/x-7z-compressed" },
    { fg = "#bb9af7", mime = "application/x-rar" },
    { fg = "#bb9af7", mime = "application/xz" },
    { fg = "#9ece6a", mime = "application/doc" },
    { fg = "#9ece6a", mime = "application/pdf" },
    { fg = "#9ece6a", mime = "application/rtf" },
    { fg = "#9ece6a", mime = "application/vnd.*" },
    { bold = true, fg = "#7aa2f7", mime = "inode/directory" },
    { fg = "#c0caf5", mime = "*" }
]

[help]
desc = { fg = "#c0caf5" }
footer = { fg = "#a9b1d6" }
hovered = { bg = "#3b4261", fg = "#c0caf5" }
on = { fg = "#bb9af7" }
run = { fg = "#7dcfff" }

[input]
border = { fg = "#7aa2f7" }
selected = { bg = "#3b4261" }
title = { fg = "#c0caf5" }
value = { fg = "#c0caf5" }

[pick]
active = { fg = "#bb9af7" }
border = { fg = "#7aa2f7" }
inactive = { fg = "#a9b1d6" }

[mode]
normal_main = { bg = "#7aa2f7", bold = true, fg = "#1a1b26" }
select_main = { bg = "#9ece6a", bold = true, fg = "#1a1b26" }
unset_main = { bg = "#f7768e", bold = true, fg = "#1a1b26" }

[status]
perm_sep = { fg = "#7dcfff" }
perm_type = { fg = "#7aa2f7" }
perm_read = { fg = "#e0af68" }
perm_write = { fg = "#f7768e" }
perm_exec = { fg = "#9ece6a" }
progress_error = { bg = "#1a1b26", fg = "#f7768e" }
progress_label = { bg = "#1a1b26", fg = "#c0caf5" }
progress_normal = { bg = "#1a1b26", fg = "#c0caf5" }

[tasks]
border = { fg = "#7aa2f7" }
hovered = { bg = "#3b4261", fg = "#c0caf5" }
title = { fg = "#c0caf5" }

[which]
cand = { fg = "#7dcfff" }
desc = { fg = "#c0caf5" }
mask = { bg = "#292e42" }
rest = { fg = "#bb9af7" }
separator_style = { fg = "#565f89" }
