accent = "#36a166"                  
active_border_color = "#5f9182"     
active_tab_background = "#302f27"

cursor = "#e7e6df"

foreground = "#dcd9d6"
background = "#22221b"

selection_foreground = "#22221b"
selection_background = "#5f9182"


# Normal colors (ANSI 0-7)
color0  = "#22221b"  
color1  = "#ba6236"  
color2  = "#7d9726"  
color3  = "#a5980d"  
color4  = "#36a166"  
color5  = "#9d6c7c"  
color6  = "#5b9d48"  
color7  = "#929181"  


# Bright colors (ANSI 8-15)
color8  = "#6c6b5a"
color9  = "#d08a65"
color10 = "#a7c957"
color11 = "#c2b53c"
color12 = "#5f9182"
color13 = "#b48495"
color14 = "#7bbf7a"
color15 = "#f4f3ec"
