# Background and foreground colors
background = #232923
foreground = #dcd6d6

# Standard colors
palette = 0=#232923
palette = 1=#c5a687
palette = 2=#8cab8f
palette = 3=#b1b195
palette = 4=#9eb8b5
palette = 5=#c5a587
palette = 6=#b0c5b9
palette = 7=#dcd9d6

# Bright colors
palette = 8=#788778
palette = 9=#c5a687
palette = 10=#c0d3c2
palette = 11=#d9d9c9
palette = 12=#d2dfde
palette = 13=#c5a487
palette = 14=#e5ece8
palette = 15=#dcd6d6
