### Read more at config document: https://github.com/limine-bootloader/limine/blob/trunk/CONFIG.md
timeout: 3
default_entry: 2
interface_branding: Omarchy Bootloader
interface_branding_color: 2
hash_mismatch_panic: no

term_background: 020007
backdrop: 020007

# Terminal colors (Purple Moon palette)
term_palette: 020007;37277d;643aad;9845c6;9b49c8;9865cf;b895dd;dfd0f0
term_palette_bright: 9c6cd0;5b43cd;a87cd8;cb97df;cd9ce1;cdb5e8;f6ebe3;ffffff

# Text colors
term_foreground: ffffff
term_foreground_bright: ffffff
term_background_bright: 24283b
